### ISSUE TITLE
[feature-request] Original files not preserved during import and library conversion

### ISSUE THREAD

**Issue by KevinKTM** [crocodilestick/Calibre-Web-Automated#103]
Maybe this is a setting I am missing but why aren't the original files getting imported along with the epub? Alot of my pdf's don't encode to epub very well so I need to keep the originals. This should really be the default behaviour.

**Comment by crocodilestick** [comment]
CWA is ereader and book 1st and so as stated throughout the README, epub is used as the primary format as it is compatible with the widest number of devices and other formats. The option to have multiple file formats for each book is to be user toggleable and is currently in the testing phase for future versions .

**Comment by crocodilestick** [comment]
As of V2.1.0, all processed files are backed up into `/config/processsed_books` by default.
