### ISSUE TITLE
[bug] Internal Server Error on Bulk upload via Web UI

### ISSUE THREAD

**Issue by kfoxton** [crocodilestick/Calibre-Web-Automated#104]
**Describe the bug**

**To Reproduce**
1. Enable Web Upload
2. Drag a bunch of epubs to the webui to upload. I have had the issue generally around 100 book mark, but have happened with less
3. Page shows uploading, then processing, then error
![image](https://github.com/user-attachments/assets/ce0cecb4-2a22-421e-b5de-7c8cc98b1d11)

**Expected behavior**
No error, reloads bookshelf.

**Configuration(please complete the following information):**
 - OS: UnRaid
 - Hardware: Intel® Xeon® CPU E5-2651 v2

**Comment by jmarmstrong1207** [comment]
This error has been fixed in the latest dev image:
` image: crocodilestick/calibre-web-automated:dev`

This is our release candidate and will be released to `latest` in the future
