### ISSUE TITLE
[Feature Request] Multiple kindle email addresses per calibrewebautomated account

### ISSUE THREAD

**Issue by yroyathon** [crocodilestick/Calibre-Web-Automated#114]
**Is your feature request related to a problem? Please describe.**
I think many people have more than one kindle.  And when they add a new book, they'd like it to be added to all their devices.  Creating multiple CWA accounts to accomplish this is probably enough hassle for folks to not do this, ie with the extra logging in and logging out.

**Describe the solution you'd like**
If the email address field could be a comma-separated list of kindle email addresses, that would be great.  Logic on the backend wouldn't have to change that much, just parsing the email field (if it contains commas) and then putting some looping structure around the send email logic.

**Describe alternatives you've considered**
Creating multiple CWA accounts.  And logging in to each and sending a book to the device.  It works, but I suspect 99% of people won't do this.  I also looked into creating a gmail distribution list to handle this, but that doesn't create a new single email address to place in an email field.  So it only works if you're manually sending an email, ie this is a solution that does not use or require CWA.

**Additional context**
I think this enhancement fits in with CWA in that, it's a convenience, it does something even better than Calibre or CalibreWeb.  This enhancement has been skipped over and closed on CW, and lots of people commented on that closed issue since, showing that there is demand for this, it is not rare.

**Comment by format0** [comment]
+1 
Just logged in to request the same feature. I am managing the kindles of multiple family members and it is a bit painful to manually switch users just to send to different email addresses. It's been requested at the CW project frequently but has never been properly added.

**Comment by crocodilestick** [comment]
This is already a feature, exactly as you requested. The Send to eReader email address field already accepts a comma-seperated list of emails and even states that in the description above the field. Simply go into the Admin panel, edit a user and add as many addresses as you want.
