### ISSUE TITLE
[bug]`convert-library --keep` Fails with AttributeError and Attempts to Convert Nonexistent Files

### ISSUE THREAD

**Issue by notsointeresting** [crocodilestick/Calibre-Web-Automated#119]
Issue: `convert-library --keep` Fails with AttributeError and Attempts to Convert Nonexistent Files

Description
When running `convert-library --keep` inside the **Calibre-Web Automated** container, I encounter an `AttributeError`:

```python
book_id = (re.search(r'\(\d*\)', file).group(0))[1:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

The script also attempts to convert files that no longer exist, suggesting that it may be pulling from an outdated cache or database.

#### Steps to Reproduce
1. Start CWA container (`crocodilestick/calibre-web-automated:latest`).
2. Run: `convert-library --keep`.
3. Observe the error and attempts to convert old, nonexistent files.

#### Troubleshooting Attempted
- Confirmed correct permissions with aligned **PUID** and **PGID**.
- Rebuilt library database in Calibre

#### Expected Behavior
The conversion script looks for non-epub files and converts. 

#### Additional Context
Running CWA on a Synology NAS via Container Manager. All containers have proper read/write access to shared volumes.
<img width="925" alt="Screenshot 2024-10-27 at 8 22 00 PM" src="https://github.com/user-attachments/assets/6140af50-759d-4d4a-acaa-8289e85316ec">
<img width="927" alt="Screenshot 2024-10-27 at 8 21 09 PM" src="https://github.com/user-attachments/assets/331d3d07-fc96-4136-ad2b-91e88750a50f">

**Comment by crocodilestick** [comment]
Hi @notsointeresting, this should be fixed in the just released V2.1.0 update
