### ISSUE TITLE
Don't waste time on Bionic Reading - it is misleading

### ISSUE THREAD

**Issue by TangentFoxy** [crocodilestick/Calibre-Web-Automated#124]
I noticed the ReadMe says you're currently working to implement Bionic Reading (although it also implies the work has completed? I'm a little confused). If it is still an active project, I would encourage you to consider abandoning the idea, as the concept as presented is not effective, and is misleading.

Font choice does affect reading speed, but Bionic Reading's claims are false.

1. [Bionic Reading is based on 12 people with mixed results](https://theconversation.com/can-bionic-reading-make-you-a-speed-reader-not-so-fast-183905). (Note that the referenced material in this article has since been removed from their website.)
2. [Bionic Reading has no impact on reading speed or comprehension](https://blog.readwise.io/bionic-reading-results/). It also requires adding a lot of bloat in markup and is patented - because it exists for profit, not usability.
   - They also link to two studies that show that **font choice does affect reading speed without negatively affecting comprehension**, but that the font that works best is highly individualized, so **there is no "one best font"**.
   - [Others found the same insignificance in results](https://qz.com/2182666/does-bionic-reading-work-typographers-and-scientists-weigh-in).
3. Two more studies showing it isn't effective: [No, Bionic Reading does not work](https://www.sciencedirect.com/science/article/pii/S0001691824001811), [Kan bionic reading bidra til økt prestasjon i leseforståelse hos sjette-trinns elever?](https://oda.oslomet.no/oda-xmlui/handle/11250/3095327) (Norweigan)

If nothing else, I hope this serves as a good reference for anyone looking into Bionic Reading, on this project or elsewhere.

**Comment by crocodilestick** [comment]
Hi @TangentFoxy, thanks for this! The processor was already built by a member of the community and won't take that much effort to implement, but as you've rightly said, it's low priority so hasn't taken away any Dev time from more important improvements/ features. As someone has already put the effort in, it'll get added at some point but mostly as a fun little add in :)

**Comment by TangentFoxy** [comment]
I assume this issue best closed then so it doesn't distract.

(Researching this to confirm my understanding was personally helpful, and I'm now writing a quick blog post about it too. :D)
