### ISSUE TITLE
Make dockerfile public

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automated#13]
The dockerfile should be made public through this repository to encourage more development from other contributors

**Comment by jmarmstrong1207** [comment]
Also what's crazy: This repository stars went up 30% since yesterday! I referenced this repo in the auto import section of the calibre-web wiki just now so there should be more users in the future. It looks like this project will be a huge success

**Comment by crocodilestick** [comment]
Hey James, I've created a Discord Server for the project, could you please join with the following link so we can coordinate better?

[CWA Discord Server](https://discord.com/invite/9Sp8gYND)

As to the dockerfile I currently don't have one to share as the stock Calibre-Web dockerfile isn't public so up to this point I've been building the modified images using `docker commit` which obviously isn't ideal.

It shouldn't be that hard but it will probably take a little time to reverse engineer one from the stock Calibre-Web repository.

**Comment by bo0tzz** [comment]
> the stock Calibre-Web dockerfile isn't public

Yes it is: https://github.com/linuxserver/docker-calibre-web

As a related note: I haven't fully understood yet how your code etc is laid out & interacts with upstream calibre-web, but from a quick look I get the impression that you're currently not in compliance with the upstream GPL license.

**Comment by crocodilestick** [comment]
Hey @bo0tzz , thanks for that! It's not on the official Calibre-Web repo and I never thought to check the linuxserver page for one. 

As to your licence query, the GNU licence clearly allows the modification and use of code to make new projects (like this one) and only doesn't allow this when using said code to make money or exclude users, which this project does not. 

See below: 

... _When we speak of free software, we are referring to freedom, not price.  Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish), that you receive source code or can get it if you
want it, that **you can change the software or use pieces of it in new free programs**, and that you know you can do these things_ ...

**Comment by bo0tzz** [comment]
You're certainly fine on that front, I'm referring to sections 5 and 6 which requires you to release your changes under the same GPL license as well. From the preamble:

> For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.

I think all you're missing is your Dockerfile and a LICENSE applying to your repository, but I figured I'd give it as a blanket statement in case there's any other components I'm not aware of.

**Comment by crocodilestick** [comment]
Ah got you! Thanks for that! Honestly I've never been great with the differences between all the licenses, I'll try and update the repo this weekend to be more compliant 👍

**Comment by Roxedus** [comment]
There is also built-in logic in the linuxserver container for modifications. https://www.linuxserver.io/custom

**Comment by crocodilestick** [comment]
> There is also built-in logic in the linuxserver container for modifications. https://www.linuxserver.io/custom

That's actually a big help, thanks for that @Roxedus 👍

**Comment by crocodilestick** [comment]
Images as of V2.0.0 are now built via Dockerfile and the Dockerfile is already freely available on the repo
