### ISSUE TITLE
[bug] "Setting up desktop integration failed"

### ISSUE THREAD

**Issue by TangentFoxy** [crocodilestick/Calibre-Web-Automated#142]
**Describe the bug**
I noticed when starting through docker-compose for the first time the following:
```
____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________

Traceback (most recent call last):
  File "calibre/linux.py", line 859, in setup_desktop_integration
  File "calibre/linux.py", line 881, in do_setup_desktop_integration
  File "calibre/linux.py", line 959, in install_xdg_junk
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command 'xdg-desktop-menu install --noupdate ./calibre-gui.desktop' returned non-zero exit status 3.
```

I don't know if I should be worried or not, but I figured I should point out that it occurred.

**To Reproduce**
1. Use docker-compose with a prexisting calibre-web library.

**Configuration(please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Hardware: x64 server

**Additional context**
~~502 Bad Gateway. :\\ No errors in the log or the reverse proxy in front of it though. *Weird.*~~ (Was a misconfiguration.)

**Comment by TangentFoxy** [comment]
The 502 without anything appearing in logs turns out to have been a misconfiguration on the container name. There is no *apparent* error in usage, but the error still appears in logs.

**Comment by crocodilestick** [comment]
> The 502 without anything appearing in logs turns out to have been a misconfiguration on the container name. There is no *apparent* error in usage, but the error still appears in logs.

Hi @TangentFoxy , this error is expected as on container init, Calibre and it's binaries are installed and as the container essentially runs on a headless version of Ubuntu, it throws up this error as it can't install it's GUI elements that are not needed.

I'll filter the error from the container logs in the next version as not too concern other users

**Comment by TangentFoxy** [comment]
> I'll filter the error from the container logs in the next version as not too concern other users

Nice, thank you!

**Comment by navels** [comment]
> I'll filter the error from the container logs in the next version as not too concern other users

@crocodilestick did you end up doing this?  I see this error in the logs and it is triggering my no-errors-no-warnings-in-logs-ocd ;-)

**Comment by My-Random-Thoughts** [comment]
Ditto, still seeing this on v4.0.6
