### ISSUE TITLE
Robotic Reading Status?

### ISSUE THREAD

**Issue by NovaCyntax** [crocodilestick/Calibre-Web-Automated#144]
I just just discovered the concept of Robotic Reading through the README on this project, and was amazed at how much easier it was to read. My system is currently ingesting my books (I have a large library) and I'm unable to access the web interface. Is this feature already present in CWA, but future optimization is planned? Apologies if this is the wrong place to ask.

**Comment by TangentFoxy** [comment]
It's low priority at the moment. See #124.

**Comment by NovaCyntax** [comment]
Thanks bro appreciate it dude
