### ISSUE TITLE
Rename scripts to a better name

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automated#22]
It's ideal to rename the script files; new-books-detector and books-to-process is ambiguous. Changing it to something else will make development easier to pickup for future collaborators

**Comment by crocodilestick** [comment]
I mean do you have suggestions?

Like honestly to me:

- A script that detects new books - new-book-detector.sh

- A script that processes new books being ingested = new-book-processor.py

- A script that identifies books in need of processing = books-to-process.sh

I'm open to all your other issues but this one 🤷

**Comment by jmarmstrong1207** [comment]
The names are ambiguous enough that I didn't understand what they did by name at all until I had to manually read the code (even when writing this comment, i had to look multiple times what each did because I'm not able to understand just by title alone). 

For example, I thought `new-book-detector.sh` was related to `new-book-processor.py`, but they aren't. `new-book-detector.py` processes books in ingest (not actually detecting the book itself) while `new-book-processor.sh` imports those already-processed books. `books-to-process.sh` does make sense, but could be changed a little. Also, it's not just new-book-detector.sh that detects "new" books, but also books-to-process, so it's ambiguous there as it depends too much on what the developer means as "new". Plus, the naming scheme is not consistent.

Instead, the scripts can be grouped into 2 categories: ingest folder scripts &  and import folder scripts (for processed books). And their names would have to related to their actions

As such, the naming scheme could be this (and the list is ordered chronologically for what scripts the book will go through to make it easier to follow):
- `books-to-process.sh` -> `ingest-processor.sh` or `ingest-processor-trigger.sh` because it's really just a trigger script for the python file
- `new-book-processor.py` -> `ingest-processor.py`
- `new-book-detector.sh` -> processed-book-importer.sh  (What it's really doing is importing books into the db)

**Comment by crocodilestick** [comment]
Done, new-book-dectector has been deprecated as of the next version, `books-to-process` is now `cwa-ingest-service` and `new-book-processor` is now `ingest-processor.py`
