### ISSUE TITLE
linux/arm64 version for docker

### ISSUE THREAD

**Issue by chrisism** [crocodilestick/Calibre-Web-Automated#23]
Is it possible to also create a linux/arm64 version for docker?

**Comment by crocodilestick** [comment]
Hey, CWA should already be arm64 compatible, test it out and let us know!

**Comment by chrisism** [comment]
Perhaps it needs an arm64 tag for the CW container. I am getting these messages after starting the docker compose.

`[+] Running 2/1
 ✔ Container calibre-web-automated                                                                                                                                      Created                               1.0s 
 ! calibre-web-automated The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                       0.0s 
Attaching to calibre-web-automated
calibre-web-automated  | exec /init: exec format error
calibre-web-automated exited with code 0`

**Comment by chrisism** [comment]
Adding platform attribute to compose yml:

`[+] Running 0/1
 ⠇ calibre-web-automated Pulling                                                                                                                                                                              1.7s 
image with reference docker.io/crocodilestick/calibre-web-automated:latest was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64`

**Comment by crocodilestick** [comment]
Ah shame, that should hopefully be fixed by an update coming soon that changes how we currently build the images. I'll add the the README when we can officially support arm64 👍

**Comment by driftywinds** [comment]
Hi, is there any update for the arm64 docker image situation?

**Comment by driftywinds** [comment]
For anyone who's interested - I built an arm64 image of CWA here - https://hub.docker.com/repository/docker/driftywinds/cwa/tags

Please try it out and let me know if it works. I just learnt how to build from a docker file though haha, but I'll try to keep the image updated with every new release

**Comment by crocodilestick** [comment]
> For anyone who's interested - I built an arm64 image of CWA here - https://hub.docker.com/repository/docker/driftywinds/cwa/tags
> 
> Please try it out and let me know if it works. I just learnt how to build from a docker file though haha, but I'll try to keep the image updated with every new release

Hey @driftywinds that's amazing! So far the main barriers have been:

- the Calibre binaries that CWA relies on are supposed to be only x86 compatible 
- I don't have any arm64 devices with which to build an arm based image

If you've managed to make a fully working arm image hats off to you and would you mind if I added links to the official repo?

**Comment by driftywinds** [comment]
> > For anyone who's interested - I built an arm64 image of CWA here - https://hub.docker.com/repository/docker/driftywinds/cwa/tags
> > Please try it out and let me know if it works. I just learnt how to build from a docker file though haha, but I'll try to keep the image updated with every new release
> 
> Hey @driftywinds that's amazing! So far the main barriers have been:
> 
> * the Calibre binaries that CWA relies on are supposed to be only x86 compatible
> * I don't have any arm64 devices with which to build an arm based image
> 
> If you've managed to make a fully working arm image hats off to you and would you mind if I added links to the official repo?

Yes go ahead for sure, you can add my links to the official repo!

Just keep in mind tho, I'm a total amateur at this and if something goes wrong I wouldn't know how to fix it. From what I understand every new update I gotta clone the git and build the image from the Dockerfile, but I wouldn't be able to fix anything if something doesn't work. 

I'm pretty sure you can somehow use GitHub Actions to build the arm64 images for you. Here is something maybe helpful I found in that regard https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

Hopefully it's useful

**Comment by carlossgv** [comment]
To add to the conversation, I managed to get the server running in my arm Oracle server using @driftywinds image.

<img width="1335" alt="image" src="https://github.com/user-attachments/assets/633c36cb-9503-4f1d-9a3b-97cff3959a7d">

However, if you think that solution is not the proper one. There is this project HortusFox and they made it working properly I think. Here is the link on that issue and in there there's the link the owner used to fix it. 

https://github.com/danielbrendel/hortusfox-web/issues/141

**Comment by crocodilestick** [comment]
> To add to the conversation, I managed to get the server running in my arm Oracle server using @driftywinds image.
> 
> <img alt="image" width="1335" src="https://private-user-images.githubusercontent.com/35035810/363419582-633c36cb-9503-4f1d-9a3b-97cff3959a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODIyODIsIm5iZiI6MTcyNjU4MTk4MiwicGF0aCI6Ii8zNTAzNTgxMC8zNjM0MTk1ODItNjMzYzM2Y2ItOTUwMy00ZjFkLTlhM2ItOTdjZmYzOTU5YTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMjE5NDFjZDMwMWE4MTY0NmRkNjNhNjAxZjhiZmM5YzU4MWNkZjFiNDIwN2JlYWY4ZDRhMzgyZTgwNTc5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06asskG1qRHBLdDlCNS4RaL0EsGsYaxUiTpK1ptA7BY"> <img alt="image" width="1528" src="https://private-user-images.githubusercontent.com/35035810/363419999-7dbcac1b-b901-47db-9de8-1b4b486f278e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODIyODIsIm5iZiI6MTcyNjU4MTk4MiwicGF0aCI6Ii8zNTAzNTgxMC8zNjM0MTk5OTktN2RiY2FjMWItYjkwMS00N2RiLTlkZTgtMWI0YjQ4NmYyNzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZmZmYmMzMmQ3MzRjNDdiYjVjYjRiNjUxNmIzMjczY2MwNmY2MWNmNGQ1ZDA5MjM0MzVlZjkzZmQ4YTE5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IPuS1iPXO54nU40wk24WpzPjZUGmdhE68j9Jy9vwSes">
> However, if you think that solution is not the proper one. There is this project HortusFox and they made it working properly. Here is the link on that issue and in there there's the link the owner used to implement it.
> 
> [danielbrendel/hortusfox-web#141](https://github.com/danielbrendel/hortusfox-web/issues/141)

Using `docker buildx` seems like a perfect solution! I'll try it out for the next version!
