### ISSUE TITLE
Removing volumes from docker does not remove them from file browser in web UI

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automated#29]
When I remove a volume from docker, it does not remove them from file browser in web UI.

For example, my library structure:
/books/
/books/librarybig
/books/librarysmall

I briefly had two volumes, one mapped to each library, but then removed them to have one volume pointing to /books

When browsing the web UI to pick a metadata.db, I see three volumes (the two old, removed ones, and the new one). Is the filesystem being cached somehow?

Also, all three folders are showing as empty, when trying to browse to point to the "Location of Calibre Database". No subfolders or anything.

**Comment by jmarmstrong1207** [comment]
This should be a problem specifically with calibre-web which this project modifies. Check out their repository
