### ISSUE TITLE
Add book file checks before removing them from the scripts & improve book file transfer

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automated#33]
Using `rm` is destructive and potentially devastating on people's data if there isn't a check to verify that the book has been successfully moved into the Calibre library. The script should check if the book was successfully imported into the library before removing the file from cwa-import

Edit:
new-book-processor.py should check if fully converted and moved to db before deleting file.

**Comment by scruffynerf** [comment]
and moving books from cwa-ingest to cwa-import can be across filesystems, not a good thing.  I realized how slow rthings were and researched to discover you move ingested books to /etc/calibre-web-automator/cwa-import which is NOT mounted, so all of that data has to enter the container, then leave.  and that'll also cause the problem of lost files, for one thing.

**Comment by jmarmstrong1207** [comment]
This issue has been fixed in v2.1.0, will move failed ingests to /config/processed_books/failed/
