### ISSUE TITLE
Edge case: If server is shut down during auto-import process, it may leave books in cwa-imports forever unless they are reimported

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automated#36]
Possible solution (?): At each startup, move the cwa-imports files back into the ingest folder for reprocessing

**Comment by crocodilestick** [comment]
Manual Library Refresh button added to UI for this and similar scenarios, together with a lock file to prevent overlapping ingests from pressing the button multiple times or pressing it while an import is in progress
