### ISSUE TITLE
[Feature Request] Include "Automated" in emails (and dark theme)

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automated#42]
There's lots of places throughout Calibre-Web which should be updated to include "Automated". For example: in emails when registering a new user, or when sending a test email.

New user:
```
Hi [*email*]!
Your account at Calibre-Web >>Automated<< has been created.
Please log in using the following information:
Username: [*email*]
Password: *****
Don't forget to change your password after your first login.
Regards,

Calibre-Web >>Automated<<
```
Test:
```
This Email has been sent via Calibre-Web >>Automated<<.
```

Also, while I know this is CA issue, not a CWA thing - why isn't there a direct link to the login page from the welcome email?

Personally, I'd love for the ability to customise all emails via the web UI, but I understand that that is a CW issue, and out of scope for CWA.

For people who might be running CW **and** CWA, this will help reduce confusion.

**Note:** yes, I have set the "From" email to be "Calibre Automated <email>", so that at least is clear. This is definitely a low priority item!

**Comment by crocodilestick** [comment]
Fixed as of V2.1.2
