### ISSUE TITLE
Memory leak during convert-library -k

### ISSUE THREAD

**Issue by Sblop** [crocodilestick/Calibre-Web-Automated#47]
Hi, Thanks for this enhancement for calibre-web. 

I am in the process of converting my library. I use the release candidate image.

I have a loot of books that it needs to convert. 20000+, so I give it time... (convert-library -k) This morning I noticed it had slowed down, in the titles it had processed during the last few ours. Also that the memory usage creapt up over 12 hours, from 400mb to around 6gb.

I have not had the time to investigate the source of this yet, but you'll need to know, before release.

Best wishes

Benjamin

**Comment by crocodilestick** [comment]
Woah crazy, 6gb?? If you have the time would you mind sending the last 1000 lines from the container logs or so? Thanks!

**Comment by Sblop** [comment]
Hi again,
Before seeing your reply I did the conversions in calibre main app, and never came back to this. Sorry for the late reply.
I have decided to close this issue, as I cannot reproduce this atm.

/B
