### ISSUE TITLE
500 Internal Server Error when opening the settings page

### ISSUE THREAD

**Issue by rursache** [crocodilestick/Calibre-Web-Automated#50]
Simply updating to v2.0.0 and opening the settings page (`/admin/view`) i'm getting this:
```
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 98, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 218, in admin
cwa_version, kepubify_version, calibre_version, lscw_version = cwa_get_package_versions()
File "/app/calibre-web/cps/admin.py", line 206, in cwa_get_package_versions
with open("/CALIBRE_RELEASE", "r") as f:
IsADirectoryError: [Errno 21] No file or directory: '/CALIBRE_RELEASE'
```

it seems to look for the `.CALIBRE_RELEASE` file which is actually in `/config/.CALIBRE_RELEASE` instead of root `/`

simply mounting that file to the path it wants fix it but this makes me feel like this repo is poorly developed or tested and i need this to be stable as multiple people depend on it

my current working docker cli command:
```sh
docker run -d \
  --name calibre-web-NAME \
  --restart unless-stopped \
  -p 8786:8083 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Bucharest \
  -v /home/radu/.calibre-web/NAME/config:/config \
  -v /home/radu/.calibre-web/NAME/import:/cwa-book-ingest \
  -v /home/radu/.calibre-web/NAME/library:/calibre-library \
  -v /home/radu/.calibre-web/NAME/config/.CALIBRE_RELEASE:/CALIBRE_RELEASE \
  crocodilestick/calibre-web-automated:latest
```

i have 3 instances running (different `NAME`s) and all these dirty fixes must be applied for all

**Comment by crocodilestick** [comment]
Hi @rursache , V2.0.0 has been in open beta for a while now and you're the first one to have this issue. Normally CALIBRE-RELEASE exists in the root directory and does for most other users. I can definitely write a fix immediately but I have no idea why this is just happening for you.

**Comment by rursache** [comment]
i think simply checking if the file exists should be enough. if no file just put version "-" like the others!
thanks for your fast response

**Comment by rursache** [comment]
one more thing, in settings under "External binaries" all the textfields are blank. 
is that normal? what are the correct paths for each? 
not sure if i should open another issue or not

![ss](https://i.imgur.com/l37N2Ve.png)

**Comment by crocodilestick** [comment]
@rursache fix is live, can you confirm it's working?

**Comment by rursache** [comment]
i can confirm the issue is fixed without mounting the file directly, thanks
