### ISSUE TITLE
[Issue] New version announcement when on the latest version

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automated#51]
Just installed the latest version, and have this at the top:

> ⚡🚨 CWA UPDATE AVAILABLE! 🚨⚡ Current - V2.0.0 | Newest - V2.0.0 | To update, just re-pull the image! This message will only display once per day

System: Synology DSM 7.2
No update was showing in Container Manager. Updated by "docker pull ...etc." CLI and then stopping, clearing and rebuilding the project. Perhaps not the smoothest way to update, but it worked.

So, yeah.

>Current - V2.0.0 | Newest - V2.0.0

Hmm.

**Comment by crocodilestick** [comment]
Made a fix, releasing in V2.0.1
