### ISSUE TITLE
[Issue] 'Title' in UI Configuration no longer works

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automated#52]
Changing the 'Title' field no longer updates the title in the UI.

<img width="498" alt="Screenshot" src="https://github.com/user-attachments/assets/dac41d2f-44d5-439a-a9f5-0e5189171564">

**Comment by iroQuai** [comment]
I guess a quick fix is possible: think it should have been better just to keep the functionality the same as the original Calibre-Web, but then just edit the predefined name (Calibre Web Automated instead of Calibre Web)

**Comment by crocodilestick** [comment]
Yeah this is something I'll make sure gets fixed in future updates

**Comment by crocodilestick** [comment]
Fixed as of V2.1.2
