### ISSUE TITLE
[Enhancement] Update CW from 0.6.22 to 0.6.23

### ISSUE THREAD

**Issue by TheDMV2** [crocodilestick/Calibre-Web-Automated#54]
I'm certain you've already flagged this, but adding it here so there's a reminder, Calibre-Web recently (3 weeks ago) was updated:

https://github.com/janeczku/calibre-web/releases/tag/0.6.23
https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.23-ls287

I know; it's regularly being updated, and synchronizing your releases to not be too far behind theirs will be difficult (and time consuming).

**Comment by crocodilestick** [comment]
Version 2.1.0 of CWA now uses CW 0.6.23 as it's base
