### ISSUE TITLE
[Feature Request] .Kepub / Kobo file format

### ISSUE THREAD

**Issue by SerinitySW** [crocodilestick/Calibre-Web-Automated#57]
Hi! Thanks for this project, it seems right up my alley and something I've been hoping for. I'd love if it supported .Kepub exports/conversions through the KoboTouchExtended plugin, available from the Calibre's "Get new plugins" listing. This would enable those with Kobos to have the best file format for their readers. [Here](https://wiki.mobileread.com/wiki/Kepub#Advantages) is a wiki listing the advantages of .Kepub files for Kobo Readers.

Personally, I don't have one myself _yet_... but I do plan on it (and some family already has some). So I couldn't quite test it with the calibre kobo sync feature yet, but I'd be happy to when the time comes!

**Comment by jmarmstrong1207** [comment]
Kepubify is already integrated with stock calibre web, and thus this project too.

The docker image comes with kepubify. Go to basic configuration -> external binaries, then set the path to /usr/bin/kepubify

**Comment by abdessalaam** [comment]
I have set the path to ``` /usr/bin/kepubify ``` but nothing happens (no option to convert a book to epub in metadata edit view). When I also set the path to calibre binaries as ``` /usr/bin ``` I see an option to convert PDF to other formats, but I guess it is from stock calibre rather than kepubify?
How to actually use kepubify?
