### ISSUE TITLE
v2.0.1 docker image not published

### ISSUE THREAD

**Issue by nareddyt** [crocodilestick/Calibre-Web-Automated#65]
It doesn't exist here: https://hub.docker.com/r/crocodilestick/calibre-web-automated/tags

Even though github shows v2.0.1 was already released

**Comment by crocodilestick** [comment]
Hi @nareddyt , as V2.0.1 is currently the latest version, it is under the "latest" tag

**Comment by nareddyt** [comment]
Hmm interesting. Do you mind if we change this tagging scheme to be standard like other projects?

Generally as soon as a release is published, the `v2.0.1` tag will be added, even if it duplicates `latest` for a short time.

The reason for this is so that users can pin to a specific version. e.g. if I pin to `latest` today, next week `latest != 2.0.1`. But I want a tag that pins to `2.0.1` specifically forever :)

**Comment by crocodilestick** [comment]
Yeah sure, I've been doing it so that a v2.0.1 tag would only exist after
it's replaced as the latest version but I can certainly change that 👍
