### ISSUE TITLE
[bug] Hitting refresh library button triggers error message

### ISSUE THREAD

**Issue by Lipown** [crocodilestick/Calibre-Web-Automated#68]
**Describe the bug**
Hitting refresh library button triggers error message

**To Reproduce**

1. Login
2. Hit Refresh Library button from top menu

**Expected behavior**
Refresh library

**Screenshots**
![image](https://github.com/user-attachments/assets/f8bf155e-54ee-4b8d-916c-403a01f9aa7c)
![image](https://github.com/user-attachments/assets/c3893742-149b-4fc0-a583-aea2822a94b1)

**Configuration(please complete the following information):**
- Docker compose stack on Ubuntu

**Comment by crocodilestick** [comment]
Hi @Lipown , could you share the container logs? The error won't show up in the one's you've shared

**Comment by JoBilert** [comment]
For me it was a rights-issue. 
I added PUID 1000 and PGID 1000 to my docker-compose and then it worked.
