### ISSUE TITLE
[bug] Exception during enforce_all_covers stopping the process for the rest of the files

### ISSUE THREAD

**Issue by leetbrown** [crocodilestick/Calibre-Web-Automated#72]
**Describe the bug**
Receiving an exception during the enforce_cover method stops the process from proceeding for the rest of the files

**To Reproduce**
1. Have an existing ebook with a very long filename for the cover 
2. execute cover-enforcer -all
3. when the file is processed you will get a file path too long error 
4. the process does not proceed for the next file

**Expected behavior**
Exception is logged but the process continues

**Screenshots**
![image](https://github.com/user-attachments/assets/5f85ea83-c27f-40c0-b496-89637d346b51)

**Configuration:**
Docker container
Version : 2.0.1

**Comment by jmarmstrong1207** [comment]
We should be able to add a try/catch block so that it'll continue if a book cover errors out like this in the meantime @crocodilestick
