### ISSUE TITLE
[Feature Request] Automatically backup ingested books

### ISSUE THREAD

**Issue by jmarmstrong1207** [crocodilestick/Calibre-Web-Automated#80]
As an extension to #33, have a backup system that will back up books to be ingested in case anything goes wrong. This is a general feature request, with no specific. Must be brainstormed for an exact implementation

**Comment by crocodilestick** [comment]
We could make a togglable setting to have the originals be stored in `/config/original-library` instead of being deleted by default

**Comment by crocodilestick** [comment]
As of V2.1.0, all processed books are now automatically backed up into `/config/processed_books` as well as automatically compressed at the end of each day to minimise disk space use and to keep things organised. Both of these features are now also able to be enabled and disabled by the user in the CWA Settings page in the Admin panel
