### ISSUE TITLE
Convert-library script fails to find books if non-default folder for books is used.

### ISSUE THREAD

**Issue by PilgrimToHyperion** [crocodilestick/Calibre-Web-Automated#82]
It isn't clear from the documentation that cwa-change-dirs must be run when changing the default books folder or convert-library will not find any books to convert.

Documentation states:

"If you ever need to change the locations of your ingest, import and/ or calibre-library folders, use the cwa-change-dirs command from anywhere within the container's terminal to open the json file where the paths are saved and change them as required."

If the user had changed the docker-compose.yml file to change the default books directory, he would probably think that convert-library would look in the books folder he chose.

It would be good if the dirs.json file is updated as part of installation based on the contents of the docker-compose.yml file's entry if changed e.g

      - /path/to/your/calibre/library:/calibre-library
      - /path/to/where/you/keep/your/books:/books #Optional

At the very least it would be a good idea to add to the documentation to run cwa-change-dirs if a non-default books folder is used.

**Comment by crocodilestick** [comment]
@PilgrimToHyperion , yeah your write, `change-dirs` is a leftover from versions of CWA where it's file structure was a bit more flexible, I'll update the README accordingly
