### ISSUE TITLE
[bug] Automatic metadata changes don't apply on bulk operations

### ISSUE THREAD

**Issue by LarryGF** [crocodilestick/Calibre-Web-Automated#85]
**Describe the bug**
When editing metadata for several books using the "Books List"  it doesn't trigger an update on the `cover-enforcer`

**To Reproduce**
1. Go to 'Books List'
2. Select one or more books and edit their metadata
3. In the container run `cover-enforcer -history` won't show the updates
4. Now go to any individual book and edit the metadata 
5. Run `cover-enforcer -history` in the container again and you will see the change in the logs

**Expected behavior**
When running the bulk edits it should trigger the metadata update

**Configuration(please complete the following information):**
 - Hardware:docker 
 - Version : 0.6.22

**Additional context**
Not sure if this should be flagged as a bug or a feature request tbh. With that said, keep up the good work, this project is amazing!

**Comment by jmarmstrong1207** [comment]
Cover enforcer is mainly for updating the book cover for kindle devices, so this isn't really a bug. Book list can't update the covers, which is why this wasn't implemented as it isn't necessary.

I'll leave this issue closed for now
