### ISSUE TITLE
[bug] Books in innaccessible folder

### ISSUE THREAD

**Issue by vazer7070** [crocodilestick/Calibre-Web-Automated#87]
**Describe the bug**

When i start the docker CWA has "calibre library"  folder but this isn't the real calibre library who is write in docker configuration.
I can change this folder with admin panel but when CWA ingest new books, they go to this folder, not mine (calibre main/calibre library).
With the docker "portainer", i have found this folder but i can't go inside with folder browser (sharing page or cloud commander docker).
the path of this volume is : **/var/lib/docker/volumes/fc0aecf70610b14ac58152771ea7e6259fdde12437f5482d2898dd42da75c6f6/_data**

**To Reproduce**
1. fix CWA with the fix of [this topic ](https://github.com/crocodilestick/Calibre-Web-Automated/issues/55)
2. Give many book to CWA for ingest
3. look on "calibre library" folder, you will see all new books

**Configuration(please complete the following information):**
 - OS:UnRaid
 - last version of CWA and calibre version from fix

**Comment by crocodilestick** [comment]
Hi @vazer7070 , could you please paste your docker compose here so I can check it?

**Comment by vazer7070** [comment]
> Hi @vazer7070 , could you please paste your docker compose here so I can check it?
you want the docker logs.?

**Comment by crocodilestick** [comment]
> > Hi @vazer7070 , could you please paste your docker compose here so I can check it?
> > you want the docker logs.?

Hi @vazer7070 , no not the logs, the compose file you used to make the container.

**Comment by vazer7070** [comment]
> > > Hi @vazer7070 , could you please paste your docker compose here so I can check it?
> > > you want the docker logs.?
> 
> Hi @vazer7070 , no not the logs, the compose file you used to make the container.

![image](https://github.com/user-attachments/assets/6907555f-bfa9-449e-9826-975c97a5284a)

**Comment by crocodilestick** [comment]
Ah okay... does unraid not support normal docker compose? Whatever your using seems to be dated as `/calibre-main/Calibre Library` hasn't been the library bind for a while now

**Comment by vazer7070** [comment]
what do you suggest then?

**Comment by jmarmstrong1207** [comment]
> what do you suggest then?

Try using the latest docker compose file https://github.com/crocodilestick/Calibre-Web-Automated/blob/main/docker-compose.yml. Let us know if you have any further issues
