### ISSUE TITLE
[bug] cover-enforcer -all throws up an error

### ISSUE THREAD

**Issue by dushyantahuja** [crocodilestick/Calibre-Web-Automated#94]
**Describe the bug**
`cover-enforcer -all` throws up the following error:

```
[cover-enforcer]: Connection with the CWA Enforcement DB Successful!
[cover-enforcer]: Enforcing metadata and covers for all books in library...
[cover-enforcer]: 3424 books detected in Library
[cover-enforcer]: Enforcing covers for 3424 epub file(s) in /calibre-library ...
Traceback (most recent call last):
  File "/app/calibre-web-automated/scripts/cover-enforcer.py", line 213, in <module>
    main()
  File "/app/calibre-web-automated/scripts/cover-enforcer.py", line 183, in main
    n_enforced, completion_time = enforcer.enforce_all_covers()
  File "/app/calibre-web-automated/scripts/cover-enforcer.py", line 104, in enforce_all_covers
    book_info = self.enforce_cover(book_dir)
  File "/app/calibre-web-automated/scripts/cover-enforcer.py", line 76, in enforce_cover
    book_id: str = (list(re.findall(r'\(\d*\)', book_dir))[-1])[1:-1]
IndexError: list index out of range
```

**To Reproduce**
1. Run cover-enforcer -all 
2. This is on the latest docker version - I have ebooks with multiple versions - many epubs and mobis

**Expected behavior**
The covers should be enforced on all the epubs. The script should ignore other versions of the ebooks. 

**Screenshots**
![Screenshot 2024-09-23 at 6 34 40 AM](https://github.com/user-attachments/assets/1f25b446-acdf-4f2c-b1c1-d4d1238b874c)

**Configuration(please complete the following information):**
 - OS: Lubuntu Server with docker
 - Hardware: x86 server
 - Version: Latest docker - CW Stock version: 0.6.22

**Comment by crocodilestick** [comment]
Hi @dushyantahuja , could you use `tree` on an author's directory in your calibre library so I can check it's file & naming structure?

**Comment by dushyantahuja** [comment]
```
Wolke, Robert/
└── What Einstein Told His Barber_ More Scientific Answers to Everyday Questions (4411)
    ├── cover.jpg
    ├── metadata.opf
    └── What Einstein Told His Barber_ More Scientific Answers to Everyday Questions - Wolke, Robert.epub

2 directories, 3 files
```

**Comment by dushyantahuja** [comment]
```
Terry Goodkind/
└── Wizard's First Rule (6120)
    ├── cover.jpg
    ├── metadata.opf
    ├── Wizard's First Rule - Terry Goodkind.epub
    └── Wizard's First Rule - Terry Goodkind.mobi

2 directories, 4 files
```

**Comment by dushyantahuja** [comment]
Let me know if you need more examples.

**Comment by jmarmstrong1207** [comment]
If you're using v2.0.1, this will be fixed in this next upcoming update. Currently, when even _one_ book does not have an EPUB file, it will stop the entire script

**Comment by jmarmstrong1207** [comment]
You can try it with docker image crocodilestick/calibre-web-automated:dev. Let us know if there are any issues

**Comment by dushyantahuja** [comment]
Works now - thanks a lot for your help.
