### ISSUE TITLE
[bug] could not locate runnable browser

### ISSUE THREAD

**Issue by pablominue** [crocodilestick/Calibre-Web-Automated#99]
**Describe the bug**
Getting could not locate runnable browser error when setting up gmail account

**To Reproduce**
1. Go to admin/Edit Email Server Settings
2. Click on Setup Gmail Account

**Expected behavior**
Google Authentication

**Configuration(please complete the following information):**
 - OS Unraid
 - Hardware: Lincstation N1
- Default instalation, gmail.json added successfully

**Additional context**

**Comment by crocodilestick** [comment]
This is an issue with stock Calibre-Web and outside of the scope of this project please make an issue there:
 https://github.com/janeczku/calibre-web/issues
